name: Build With Gradle

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Archive artifacts (Bungee)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: BungeeTabListPlus Bungee
          path: bootstrap-bungee/build/libs/BungeeTabListPlus-*-SNAPSHOT.jar

      - name: Archive artifacts (Bukkit)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: BungeeTabListPlus Bukkit Bridge
          path: bootstrap-bukkit/build/libs/BungeeTabListPlus_BukkitBridge-*-SNAPSHOT.jar

      - name: Archive artifacts (Fabric 1.16.3)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: BungeeTabListPlus Fabric 1.16.3 Bridge
          path: fabric-bridge-1.16.3/build/libs/btlp-fabric-bridge-*-SNAPSHOT.jar

      - name: Archive artifacts (Fabric 1.17)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: BungeeTabListPlus Fabric 1.17 Bridge
          path: fabric-bridge-1.17/build/libs/btlp-fabric-bridge-*-SNAPSHOT.jar